<?php

 $name = 'Edit person';
 $this->headTitle($name);
 ?>
 <h1><?php echo $this->escapeHtml($name); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'person',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('surname'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();